[main]
demo = false

[pinecone]
api_key = "pcsk_7VkStS_ifR3SH9d1MSkkju9kP7DUt5M16CpNyzi9dwNBm7iUqyXmbKZWQbC55ZzfSEaAB"
aws_region = "us-east-1"
index_name = "mirra-filtering"
sagemaker_endpoint = "e5-embeddings-huggingface"
namespace = ""
in_use = true

[openai]
api_key = "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"

[aws]
path=""
bucket_name="mirra-matcher-325"
file_key="data/raw/final_inference_data.xlsx"

[model]
token="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"
