[main]
demo = false

[pinecone]
api_key = ""
aws_region = "us-east-1"
index_name = "mirra-filtering"
sagemaker_endpoint = "e5-embeddings-huggingface"
namespace = ""
in_use = true

[openai]
api_key = ""

[aws]
path=""
bucket_name="mirra-matcher-325"
file_key="data/raw/final_inference_data.xlsx"

[model]
token="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"
