[pinecone]
api_key = ""
aws_region = "" 
index_name = "mirra-filtering"
sagemaker_endpoint = ""
namespace = ""

[openai]
api_key = ""

[aws]
path=""
bucket_name=""
file_key="data/raw/sample_des_extractions_test_final_3.25.25.xlsx"

[model]
token="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"